from __future__ import annotations

from typing import Literal, TypeVar

DOMAIN_TIME = "DOMAIN_TIME"
DOMAIN_LEN = "DOMAIN_LEN"

VALID_DOMAINS = (DOMAIN_TIME, DOMAIN_LEN)
Domains = Literal["DOMAIN_TIME", "DOMAIN_LEN"]

POINT_START = "SHOT_START"
POINT_PEAK_AVG = "PEAK_AVG_P"
POINT_PEAK_BREECH = "PEAK_BREECH_P"
POINT_PEAK_SHOT = "PEAK_SHOT_P"
POINT_FRACTURE = "FRACTURE"
POINT_BURNOUT = "BURNOUT"
POINT_EXIT = "SHOT_EXIT"
POINT_PEAK_STAG = "PEAK_STAG_P"
SAMPLE = "SAMPLE"
COMPUTE = "COMPUTE"

Points = Literal[
    "SHOT_START",
    "PEAK_AVG_P",
    "PEAK_BREECH_P",
    "PEAK_SHOT_P",
    "FRACTURE",
    "BURNOUT",
    "SHOT_EXIT",
    "PEAK_STAG_P",
    "SAMPLE",
    "COMPUTE",
]

SOL_LAGRANGE = "SOL_LAGRANGE"
SOL_PIDDUCK = "SOL_PIDDUCK"
SOL_MAMONTOV = "SOL_MAMONTOV"

VALID_SOLUTION_METHODS = (SOL_LAGRANGE, SOL_PIDDUCK, SOL_MAMONTOV)
Solutions = Literal["SOL_LAGRANGE", "SOL_PIDDUCK", "SOL_MAMONTOV"]

VALID_PRESSURE_POINTS = (POINT_PEAK_BREECH, POINT_PEAK_SHOT, POINT_PEAK_AVG, POINT_PEAK_STAG)

GUN_PEAK_POINTS = (POINT_PEAK_AVG, POINT_PEAK_SHOT, POINT_PEAK_BREECH)
GunPeakPoints = Literal["PEAK_AVG_P", "PEAK_SHOT_P", "PEAK_BREECH_P"]

RECOILLESS_PEAK_POINTS = (POINT_PEAK_AVG, POINT_PEAK_SHOT, POINT_PEAK_BREECH, POINT_PEAK_STAG)
RecoillessPeakPoints = Literal["PEAK_AVG_P", "PEAK_SHOT_P", "PEAK_BREECH_P", "PEAK_STAG_P"]

MIN_BARR_VOLUME = "MIN_BARR_VOLUME"
MIN_PROJ_TRAVEL = "MIN_PROJ_TRAVEL"
VALID_OPT_TARGETS = (MIN_BARR_VOLUME, MIN_PROJ_TRAVEL)
OptimizationTargets = Literal["MIN_BARR_VOLUME", "MIN_PROJ_TRAVEL"]

CONVENTIONAL = "CONVENTIONAL"
RECOILLESS = "RECOILLESS"
VALID_GUN_TYPES = (CONVENTIONAL, RECOILLESS)
GunTypes = Literal["CONVENTIONAL", "RECOILLESS"]

MAX_ITER = 10


T = TypeVar("T")


class JSONable:
    def to_json(self) -> str:
        raise NotImplementedError

    @classmethod
    def from_json(cls: T, json_dict: dict) -> T:
        raise NotImplementedError
